### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by jangjue** [sweatshops/uPush_APK#2]
![img_3473](https://cloud.githubusercontent.com/assets/20177944/16402168/1018f2ca-3d1d-11e6-8fb1-936b29857cbc.PNG)

What error is this ?
I have a working Wifi

**Comment by joscmw95** [comment]
Hi, uPush has stopped its service since the beginning of the May 2016 semester. The reasons of it and details can be learnt at our Facebook page here: https://www.facebook.com/upushie/?fref=ts
